<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="turtle">
    <xacro:property name="yaml_file" value="$(find package)/config.yaml" />
    <xacro:property name="turtle" value="${load_yaml(yaml_file)}" />
    <xacro:property name="myprop"  value="${props['myprop']}" />
    <xacro:property name="width" value="0.5"/>
    <xacro:property name="length" value="0.1"/>
    <xacro:property name="pradius" value="0.35"/>
    <xacro:property name="sradius" value="0.1"/>
    <xacro:property name="wradius" value="0.3"/>
    <xacro:property name="force" value="100.0"/>
    <xacro:property name="max_velocity" value="0.22"/>

    <material name="blue">
        <color rgba="0 0 1.0 1.0"/>
    </material>
    <material name="red">
        <color rgba="1.0 0 0 1.0"/>
    </material>
    <material name="green">
        <color rgba="0 1.0 0 1.0"/>
    </material>
    <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
    </material>

    <link name="base_link">
        <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="${width} ${width} ${width}" />
        </geometry>
        <material name="blue"/>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/> 
            <geometry>
                <box size="${width} ${width} ${width}"/>
            </geometry>
        </collision>
    </link>

    <link name="platform">
        <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <cylinder radius="${pradius}" length="${length}" />
        </geometry>
        <material name="green"/>
        </visual>

        <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="${pradius}" length="${length}"/>
        </geometry>
        </collision>
    </link>

    <link name="fix_link">
        <visual>
        <origin xyz="0 0 0.425" rpy="0 0 0" />
        <geometry>
            <cylinder radius="${sradius}" length="0.35" />
        </geometry>
        <material name="red"/>
        </visual>

        <collision>
            <origin xyz="0 0 0.425" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${sradius}" length="0.35" />
            </geometry>
        </collision>
    </link>

    <link name="stem">
        <visual>
            <origin xyz="0 0 -0.325" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${sradius}" length="0.15" />
            </geometry>
            <material name="red"/>
        </visual>

        <collision>
            <origin xyz="0 0 0.325" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${sradius}" length="0.15"/>
            </geometry>
        </collision>
    </link>

    <link name="wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0" />
            <geometry>
                <cylinder radius="${wradius}" length="0.1" />
            </geometry>
            <material name="black"/>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 1.57 0"/>
            <geometry>
                <cylinder radius="${wradius}" length="0.1" />
            </geometry>
        </collision>
    </link>

    <joint name='base_fix_link' type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="fix_link"/>
    </joint>

    <joint name='link_platform1' type="continuous">
        <origin xyz="0 0 ${width+0.35/2}" rpy="0 0 0"/>
        <parent link="fix_link"/>
        <child link="platform"/>
        <axis xyz="1 0 0"/>
    </joint>

    <joint name='base_stem' type="continuous">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="stem"/>
        <axis xyz="0 0 1"/>
    </joint>
    
    <joint name='stem_wheel' type="continuous">
        <axis xyz="1 0 0"/>
        <limit effort="1000.0" velocity="${max_velocity/wradius}"/> 
        <parent link="stem"/>
        <child link="wheel"/>
        <origin xyz="0 0 -0.7" rpy="0 0 0"/>
    </joint>
        
</robot>    
